### ISSUE TITLE
[TASK][CORE-02.T06] Implement reference-safe retention and deletion

### ISSUE THREAD

**Issue by Jordan-Hall** [Jordan-Hall/browser#134]
Parent: #3

Task ID: `CORE-02.T06`

Review: pending
Implementation: not started

Source: task breakdown from the implementation handbook and the parent issue implementation proposal.

**Comment by Jordan-Hall** [comment]
## Review — CORE-02.T06

Parent: #3. The implementation PR is **#801**, reviewed at `fbfcfceb17540e5fe80bec555385e097f3787455`; the issue body's PR-pending text is stale. This review does not alter that body.

**Confirmed P1 blocker:** suppression updates an INSTEAD OF-triggered view, then expects one affected row. SQLite reports zero for the outer statement, so the method returns ConcurrentSuppression and rolls the transaction back. Latest inspected CI run `35086737317`, job `104763204222`, passes formatting/Clippy but fails all three retention tests with this error. An independent SQLite reproduction confirms the trigger/row-count behavior. Update the scoped base table under transaction or verify the logical result without relying on view changes counts; do not weaken the tests.

**Additional blockers:** selecting a limited sorted prefix before checking eligibility can indefinitely starve later eligible blobs. Use an eligibility-filtered/keyset scan and bounded retries. GC also unlinks before its second eligibility check; without a real profile-wide owner or deletion-generation exclusion, another writer can add a hold/live handle between the first check and unlink. Detecting that afterward cannot restore the file.

**Representation:** suppression is encoded as a fake negative byte_size in a view, not an explicit lifecycle result. Keep normal hidden data, administrative retention access and actual corruption distinct, with scoped tombstone semantics.

**Acceptance:** all three current tests green; retained-prefix scan beyond 64 records; live handles/references/holds; ingestion or hold addition racing GC; restart before/after unlink; failure backoff; missing-file reconciliation; active-reader and ID-reuse policy. Full findings and original review-thread references are on #801.

This task is not complete while suppression fails and the latest tested head is red. Review only; no fix or status change claimed.

**Comment by Jordan-Hall** [comment]
## Review follow-up — CORE-02.T06 remains blocked

Parent: #3. Implementation PR is #801; the issue body's “PR: pending” is stale. Current reviewed head `fbfcfceb17540e5fe80bec555385e097f3787455` has three failing retention tests, not a completed retention implementation.

Additional review: https://github.com/Jordan-Hall/browser/pull/801#issuecomment-5706541001 . Besides the existing first-suppression rollback, starvation and GC/hold race findings, expiry pruning currently processes all expired holds before checking the batch limit; even limit zero mutates state. Bound this maintenance work separately.

The GC failure logger also truncates a String at byte 2048 without a UTF-8-boundary check. Add a Unicode error regression so recording a deletion failure cannot itself panic. Keep explicit known-committed versus rollback outcomes when suppression/reference/hold changes commit before enqueue.

Acceptance must also include #133's false-reference-success case: GC may only rely on pins proven to exist. Preserve failing tests, fix the underlying transactional/lifecycle behavior, and link rerun evidence. This comment does not implement or mark any finding fixed.
